CREATE DATABASE user_management;


USE user_management;

CREATE TABLE IF NOT EXISTS users(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE
);

-- Insert

MERGE INTO  users(id,username,password,email) KEY(id) VALUES (1,'Muhammet','123456','akdumanmuhammet34@gmail.com')

--select

select * FROM users;

--find user

SELECT * FROM users WHERE username = "Hamit"  AND "123456";

--update

UPDATE users SET username = "Muhammet2525", password = "12345666", email="akdumanmuhammet3425@gmail.com" WHERE id=1;

--delete
DELETE FROM users WHERE id = 1;